### ISSUE TITLE
Create access management policies for github.com/ossf

### ISSUE THREAD

**Issue by steiza** [ossf/tac#164]
This work was in-flight before the new TAC was seated, see https://github.com/ossf/tac/pull/155.

There's essentially two parts:
- Having repo membership managed by teams instead of individual accounts
- Should anyone be able to join github.com/ossf (to display a badge on their GitHub user profile)

**Comment by ljharb** [comment]
I'd be happy to find time to attend a TAC meeting if either of these points receive pushback, to argue in favor :-)

**Comment by SecurityCRob** [comment]
I agree that permission should be managed through roles/groups and not via individual entitlements.  Can we get some folks to donate some time in assisting with the repo review and implementation of changes if the TAC approves?

**Comment by lehors** [comment]
Is there any downsides to this (other than requiring some work to implement it)?

**Comment by ljharb** [comment]
I'm also able to help; I've already spent a bunch of time doing this auditing.

**Comment by hythloda** [comment]
I made the first pass of this for all the repositories in ossf.  All individuals have been put on a team with similar access. If there are any problems with this you can ping me on slack or email us at operations@openss.org

I decided to remove individuals from the repo rather than wait for them to join the team so that we can move this more quickly.  Some contributors are no longer active and I did not want the process held up.

**Comment by lehors** [comment]
SGTM. Thanks Amanda!

**Comment by steiza** [comment]
Both https://github.com/ossf/tac/pull/155 and https://github.com/ossf/tac/pull/171 have landed.
