### ISSUE TITLE
Review WG proposals for adopting LF and CII initiatives

### ISSUE THREAD

**Issue by kaywilliams** [ossf/tac#25]
For the [10/30 planning milestone](https://github.com/orgs/ossf/projects/1), the strategy committee would like to announce [consolidation of OpenSSF, LF and CII initiatives](https://github.com/ossf/gb-strategy-committee/issues/8).

Several of the WG's (Best Practices, Identifying Security Threats and Critical Projects) are or will be investigating adoption of the [identified initiatives](https://docs.google.com/document/d/1fKoriYszCEYuNsj1v44LxfBmLEuMqjos21Yc_iEGB0w) into their own.

This issue is a placeholder for the TAC to review and approve WG proposals, ideally by the 10/6 meeting.

**Comment by dlorenc** [comment]
Opened https://github.com/ossf/wg-securing-critical-projects/issues/14 to track the Census part.

**Comment by dlorenc** [comment]
Since we still haven't established a process for reviewing/approving things in WGs, or what type of things need approval, I'd rather we don't actually formally approve anything.

WGs should be fairly autonomous IMO. If we decide to vote now, let's make sure we quickly follow that up with the rest of the process and explain why we're reviewing these things as opposed to the other ongoing WG activities.

**Comment by david-a-wheeler** [comment]
See also the related [TAC issue 25](https://github.com/ossf/tac/issues/25).

**Comment by kaywilliams** [comment]
Circular reference?

**Comment by david-a-wheeler** [comment]
I would say "cross-reference" :-).

**Comment by dlorenc** [comment]
This is completed now, correct?

**Comment by david-a-wheeler** [comment]
Yes, I think we can close this. @kaywilliams ?
