### ISSUE TITLE
TAC/Staff interlocks

### ISSUE THREAD

**Issue by sevansdell** [ossf/tac#269]
The TAC would like to invite staff stakeholders: Chief Architect, Ecosystem Strategist and Community Engagement Manager to present to the TAC their 2024 outcomes so that the TAC can both support with and interlock with those roles. The TAC believes these roles are critical to OpenSSF, and requested them from the GB in the November 2022 meeting. 2023 was a great year as you all came on board and acclimated. In 2024, we want to work together to do great things.

Formalizing a Slack thread with TAC/Chief of Staff into a Github issue.

**Comment by CoS-Harry** [comment]
@sevansdell can you please clarify "...present to the TAC their 2024 outcomes..." as outcomes indicated something has occurred. Dana is working on the Security Baseline project and Bennett is working on the Package Manager Forum project. I believe the TAC has already been briefed on these projects.

**Comment by SecurityCRob** [comment]
I think that having the Staff show up, sharing what their goals are and progress on assorted projects would be extremely useful to the community.  We haven't heard about the Baseline project since last year and the Package Manager Forum is unfamiliar to me personally, maybe others are more in the loop.

Just like our TIs quarterly reporting, I think it is important to share updates to our community on what the Foundation Staff is working on and where we all might contribute or learn more.

**Comment by sevansdell** [comment]
Closing this issue for lack of traction over the last two months -  we can reopen it or start a new one in the future if more formal TAC/staff interlocks are specifically identified. For now, TAC calendar reserves time each TAC meeting informally for staff to share what they're doing for awareness if desired, and issues are opened by staff for more formal TAC interlocks.
