### ISSUE TITLE
Alignment between lifecycle and staff support

### ISSUE THREAD

**Issue by omkhar** [ossf/tac#308]
Hi folks,

I'd like to chat about the kind of support the OpenSSF staff can provide projects based on the [gives and gets](https://github.com/ossf/tac/blob/main/process/TI-Gives%2BGets.md). 

Specifically, we're looking to understand how we should prioritize our PMO resources for meeting planning, agenda, minutes etc across our wide variety of projects, workgroups and SIGs.

After discussion, my goal would be to update the [gives and gets document](https://github.com/ossf/tac/blob/main/process/TI-Gives%2BGets.md) with our new understanding.

**Comment by omkhar** [comment]
Also, swag, stickers etc (proposed to provide this at incubate and above, once they are granted a logo)

**Comment by adityasaky** [comment]
I think it'd be nice to have stickers for sandbox projects that have a logo, with other swag for incubating and above.

Disclaimer: I maintain a sandbox project at the OpenSSF.

**Comment by omkhar** [comment]
I'd like to get a priority list from the TAC. From there staff can prioritize our budget to meet the need. I presume the priority will be in decreasing order of maturity, for obvious reasons. We should also agree as to whether there will be a minimal bar (you must at least be at phase X).

**Comment by kairoaraujo** [comment]
> I think it'd be nice to have stickers for sandbox projects that have a logo, with other swag for incubating and above.
> 
> Disclaimer: I maintain a sandbox project at the OpenSSF.

+1 here :)

**Comment by sevansdell** [comment]
Initial thoughts:

Baseline PMO for all TIs at starting at sandbox would be mailing list/slack channel/calendar invite/google drive/initial agenda template./github SIG chair/co-chairs can email operations@openssf.org for assistance as needed ad hoc.

For more formal PMO support (preparing meeting agenda template, etc [need list of things PMO helps do today to capture what this is please @hythloda], reserve for incubating/graduated WGs and Projects.  

If at incubating stage you have a logo, can request stickers. If at graduated stage, can request additional swag [what are examples to list here if any @hythloda].

**Comment by omkhar** [comment]
@sevansdell I would prefer a stack ranked list of how the TAC would like TIs supported from PMO by maturity level / type (projects, wg, sig). What you're proposing may exceed our current capacity. I'd like to come back to you with where the "cut line" is with current staffing, as well as what our options might be to achieve what you'd like. I will manage this from a staff perspective, please work with me.

Same applies to swag. In the grand scheme of things we'd love for everyone to have all the swag all the time. However, our budget will not allow for that. If we could establish an ear mark based on project maturity it may also help encourage TIs to complete the pre-requisite tasks to "unlock" marketing dollars for swag.

I hope that helps, I look forward to our discussion.

**Comment by hythloda** [comment]
> Initial thoughts:
> 
> Baseline PMO for all TIs at starting at sandbox would be mailing list/slack channel/calendar invite/google drive/initial agenda template./github SIG chair/co-chairs can email [operations@openssf.org](mailto:operations@openssf.org) for assistance as needed ad hoc.
> 
> For more formal PMO support (preparing meeting agenda template, etc [need list of things PMO helps do today to capture what this is please @hythloda], reserve for incubating/graduated WGs and Projects.
> 
> If at incubating stage you have a logo, can request stickers. If at graduated stage, can request additional swag [what are examples to list here if any @hythloda].

Sarah that list is spot on, in our project onboarding checklist, we have a similar one:

> Discuss with the maintainers and see what they want from the OpenSSF to start have a discussion, for example, about:
Slack Channels
GitHub Enterprise under OpenSSF (AFTER CHARTER and Contribution Agreement)
LFX Zoom
Meeting notes
Google Drive Folder
Community Calendar
PCC groups (plus mailing list)
      --Voting or not?

We will generally have a PMO attend the meetings until the charter is approved to help through that process.

I envision this list is the same for WG and SIGS aside with non-projects we also offer to make GitHub repos and teams. 

For additional support, we can have things like 
PMO attending meetings for notes help
Coordinate agendas
Set up a Community Manager for making meetings in PCC. 

Since I was pinged on this, I will add my 2 cents on swag. One of the hardest parts of becoming incubating is getting your project adopted by multiple parties. A number of elements need to be done for the sandbox that it is not easy, getting the INFRA set up, Charter, Contribution Agreement, etc. Having the LF design team make a logo and stickers after the sandbox elements are complete is a good reason for finishing the sandbox process (maybe cap it at $150 a year). Having a logo+stickers helps community engagement (part of our roadmap) and will help with adoption streamlining the ability to become inbutaing. 
Then, keeping higher level swag for incubating and graduated, of course.  So logo for all (unless we start getting many projects a month), sandbox capped at $150 a year, incubating ?? graduated ??

**Comment by lehors** [comment]
> If we could establish an ear mark based on project maturity it may also help encourage TIs to complete the pre-requisite tasks to "unlock" marketing dollars for swag.
> 

This is indeed a key principle of the TI lifecycle and the gives-and-gets. We need to ensure that there is some incentive to work on progressing a TI to greater maturity levels.

**Comment by sevansdell** [comment]
With PMO staff being limited, after the conversation in our TAC meeting, April 30, I would ask that PMO support Working Groups. I would like to see them help with horizontal and vertical interlocks. Horizontal: alignment up and down the projects and SIGs in a WG. Vertical: alignment across WG. 

What do I mean by alignment? Open to evolving the definition here with input. But instead of copying/pasting the agenda and capturing notes during calls, I think more of working in tight alignment with WG leads to facilitate these horizontal and vertical interlocks. They could also interlock with staff roles for chief architect, ecosystem strategy and community engagement. And the TAC/committees of the board where needed. As OpenSSF has grown over time through a community of volunteers, the TAC and WG leads needed staff support to engage with other. This was an ask to GB back in October 2022, and I would like to see us partner together to facilitate WG engagements. 

I am going to cross post to an ask that may appear unrelated at first: should projects report to the TAC or a WG? https://github.com/ossf/tac/issues/325. I am recommending WG, because with PMO engagement, the support a WG can provide a project across the OpenSSF will be a value-add.

**Comment by SecurityCRob** [comment]
TI Support Reference
This is the suggested approach to prioritize staff involvement in foundation efforts.  Moving from most engaged to leas engaged...
1. Board Committees/Councils
2. Working Groups
3. Projects
4. SIGs
 

TI Maturity Levels
In support of TIs, staff should prioritize using the maturity level of the TI, moving from highest-engagement with Graduated, down to lower levels for newer efforts, where engagement, outside of operation support (like assisting in getting calendar invites or a mailing list setup) would be ad hoc.
1. Graduated
2. Incubating
3. Sandbox

**Comment by omkhar** [comment]
hey @sevansdell and @SecurityCRob, there are three separate statements here which I'd like to reconcile.

1. @SecurityCRob has prioritized the existing PMO tasks by TI maturity (the original intent of this issue).
2. @sevansdell has requested an additional set of tasks to be done by PMO (interlocks?) based on a discussion from 2022 October
3. @sevansdell has also asked a question about reporting hierarchy (projects reporting to TAC or WG)

I'm happy to prioritize (1) as requested.
(2) May require a different set of program management resources and labor mix within staff. This might be more of a medium term goal. @sevansdell could you start by documenting the new tasks in a 1-pger? As this may be budget impacting, I'd like to target this to our 2025 budget.
(3) I don't have an opinion and I am happy for the TAC to advise how they'd like to proceed.

If we're in agreement, I'll close this issue as it was primarily opened to address (1). aiming to close by 05/22 if I do not hear otherwise.

**Comment by omkhar** [comment]
@SecurityCRob  did we also confirm that SWAG is for projects at Sandbox+ ?

**Comment by SecurityCRob** [comment]
> @SecurityCRob did we also confirm that SWAG is for projects at Sandbox+ ?

According to https://github.com/ossf/tac/blob/main/process/TI-Gives%2BGets.md#getsbenefits, Sandbox was not written up as eligible for custom swag.  At Incubating we note that they can request a customer logo, but no mention of swag.  I feel that Incubating demonstrates enough longevity that we would consider customer swag (low cost....stickers, book marks, ribbons).

**Comment by SecurityCRob** [comment]
> hey @sevansdell and @SecurityCRob, there are three separate statements here which I'd like to reconcile.
> 
>     1. @SecurityCRob has prioritized the existing PMO tasks by TI maturity (the original intent of this issue).
> 
>     2. @sevansdell has requested an additional set of tasks to be done by PMO (interlocks?) based on a discussion from 2022 October
> 
>     3. @sevansdell has also asked a question about reporting hierarchy (projects reporting to TAC or WG)
> 
> 
> I'm happy to prioritize (1) as requested. (2) May require a different set of program management resources and labor mix within staff. This might be more of a medium term goal. @sevansdell could you start by documenting the new tasks in a 1-pger? As this may be budget impacting, I'd like to target this to our 2025 budget. (3) I don't have an opinion and I am happy for the TAC to advise how they'd like to proceed.
> 
> If we're in agreement, I'll close this issue as it was primarily opened to address (1). aiming to close by 05/22 if I do not hear otherwise.

We discussed #3 yesterday in the TAC call, and is being tracked by https://github.com/ossf/tac/issues/325 .

**Comment by omkhar** [comment]
As per https://github.com/ossf/tac/issues/308#issuecomment-2111331131 I'm closing this issue. thanks for all the input, I will raise PRs to make the recommended changes to our documentation

**Comment by sevansdell** [comment]
I am comfortable closing this with item 1 resolved and item 3 in a new PR.  Any action on 2, proposed interlocks between TIs supported by PMO, I am not going to pursue at the moment. Thanks!

**Comment by omkhar** [comment]
https://github.com/ossf/tac/blob/main/process/TI-Gives%2BGets.md has been updated per this discussion
