### ISSUE TITLE
Publish TI funding requests cycles.

### ISSUE THREAD

**Issue by marcelamelara** [ossf/tac#336]
As announced in [this](https://openssf.org/blog/2024/03/19/how-openssf-technical-initiatives-can-receive-strategic-funding/) blog post, the TAC will review TI funding requests as a batch on a quarterly basis starting in Q2 2024.

Dates that needs to be published on the TAC repo and amplified on Slack for each cycle:
* Submission cycle open
* Submission deadline
* Decisions announced

**Comment by steiza** [comment]
We are rapidly approaching the mid-June window mentioned on the [blog post](https://openssf.org/blog/2024/03/19/how-openssf-technical-initiatives-can-receive-strategic-funding/)!

Because of the tight timeline, I'm going to propose a schedule and ask that OpenSSF staff help us make this a reality. Copying over the steps from last time:

> Get form online, communicate a call for Proposals

The form is https://github.com/ossf/tac/issues/new?template=funding_application.yml, can OpenSSF PMO / Marketing help us communicate out the call for proposals?

> Proposal submission period 

That would be right now until when? Maybe Friday June 7th, so we can review before the June 11th TAC call?

> TAC proposal review (may need a special session)

Monday June 10th, through the Tuesday June 11th TAC call with follow-up async voting until Friday June 14th?

> Notify accepted/non acceptance proposals in writing; begin funding conversations; 

This could be June 17th - 21st?

> Publish accepted proposals online and announce with [CNSC NA](https://events.linuxfoundation.org/cloudnativesecuritycon-north-america/)

That would be June 26th - 27th?
