### ISSUE TITLE
Advice Needed - Staff-Produced Architecture Document Review Process 

### ISSUE THREAD

**Issue by Danajoyluck** [ossf/tac#361]
Right now it's difficult to for people interested in participating with OpenSSF to determine how to participate or what to use.

I'm working on a consumption architecture for the technologies we produce at the OpenSSF and the foundational OSS technologies that OpenSSF uses. The goal of this artifact would be to provide an easy model for our end user organizations large and small to have a framework / reference architecture to help them think about adopting OpenSSF technical projects and guidance. Another goal is to make it easier for people to contribute to our technologies. 

The draft is here: https://github.com/Danajoyluck/openssf-tac/blob/main/consumption-architecture-dependency-management.md

I will need advice from TAC:
1. Does TAC need to review and approve the document?
2.  Is TAC repo the home for this document?
3.  OR is the new Security Baseline SIG the proper repo for the architecture documents? The SIG was newly created in the BEST Working Group and @SecurityCRob is the sponsor. See [BEST WG issue](https://github.com/ossf/wg-best-practices-os-developers/issues/562) for details.

**Comment by sevansdell** [comment]
At first glance, this "feels" like an extension of the https://github.com/ossf/Diagrammers-Society and then the CICD extension of the [security toolbelt](https://github.com/ossf/toolbelt)? Since both of those projects have archived due to lack of engagement, I'm glad to see the OSSF architect continuing on this good work.

Classically, we have two types of stakeholders:
-Maintainers of OSS projects (producers)
-Enterprises using OSS projects (consumers)

When I looked at the linked Word document, it wasn't clear to me if it applied to our producer or consumer stakeholders or both. I recommend identifying who this document will serve (producers, consumers or both).

That helps with the other follow up questions:

1. I believe you need to find a Technical Initiative where this work can live. The TAC will get informed about your work with the community in TAC updates from whichever working group you partner with. In the past, both the Diagrammer's Society and SEcurity Toolbelt lived in the BEST WG.
2. I believe the Technical Initiative with which you work with other community members should house documents you create in partnership with them in their repo. Doesn't _need_ to be in the TAC repo.
3. The security baseline SIG (my understanding) was how producers could apply a security baseline to their project (starting with OSSF projects first, but then going on to other LF OSS projects). Are you wanting to increase the Security Baseline SIG scope to incorporate how End Users (consumers) can interact with OSSF? Perhaps that might be a good conversation for the End Users WG? I also know that Dr. Martin had a ppt that each OSSF member could see that shared how to get started. It leveraged the CICD view from the Diagrammer's Society, and could also leverage the updating work you are doing. I recommend coordinating with her too. 

I think your documentation does need a home, and your efforts to coordinate should pay off with continued coordinating with staff/other TIs.

**Comment by Danajoyluck** [comment]
Thanks a lot @sevansdell for the detailed response....very helpful information. Thank you for sharing the other efforts. 

I mistakenly attached the wrong ling to the issue. I have corrected it. Here is the draft I'm working on, it's mainly diagrams and I'm filling in the contents.

The [intended audience](https://github.com/Danajoyluck/openssf-tac/blob/main/consumption-architecture-dependency-management.md) are OSS producers and consumers. The architecture aims to help OSS producers to producer more secure code, and consumers to consume more secure OSS. 

This architecture complements the security baseline. They go hand in hand with each other to increase the adoption of OpenSSF technologies. It seems the Security baseline SIG is a good home for this architecture document? The SIG is under the BEST WG that has been building the foundation of the architecture.

**Comment by sevansdell** [comment]
Dana - Did a quick scan of the diagrams. At first glance, they look outstanding! 

If you put this documentation in the security baselines SIG repo, be sure the scope of the SIG includes both producers and consumers, and that it will include broad diagrams for both personas. Right now, I believe the security baseline SIG seems geared towards producers vs consumers, but as long as you keep the scope updated in the SIG repo home page, and keep the Best WG lead updated, that _could_ be it's home for now. 

During the next weeks and months, I recommend keeping in touch with the BEST WG and End Users WG, announcing the status of the diagrams in your TAC staff update section, and communicate with MAC and DevRel communities.  I believe over time, you will find all of these teams will participate in various ways.

Thanks for your leadership.

**Comment by Danajoyluck** [comment]
@sevansdell thank you Sarah for the advice! Glad you appreciate the diagrams. Very helpful. I will sync up with CRob and Jacques.

**Comment by Danajoyluck** [comment]
closing the issue, will check the document into Security Baseline SIG repo. Many thanks to @sevansdell for your prompt support!
