### ISSUE TITLE
Define Active Working Group Abilities

### ISSUE THREAD

**Issue by dcmiddle** [ossf/tac#44]
When a working group reaches Active state it should have latitude to accomplish its work, only seeking TAC or Governing Board approval for limited cases.

Consider what creates the most efficiency for adding value to the open source community balanced with what oversight ensures the most quality.

Some example items for consideration:
- Projects
- Papers
- Repositories
- Funding

_Here are some opinions to get the conversation started (the word Active is omitted below for brevity)..._

**Projects**
The TAC authorizes all Technical Initiatives including projects. However the working groups are intended to be the subject matter experts in their domains. Consequently, Projects should be proposed to Working Groups who will then vet and/or revise the proposals before recommending them to the TAC.

**Papers**
As the working groups are intended to be the subject matter experts in their domains, they should author papers for release through the OpenSSF without TAC approval. All papers should still follow open source best practices including transparency in development and avoiding vendor bias.
_(Note that at this time the OpenSSF is also considering a committee to review white papers. If that is approved then all authors would submit for review through that committee.)_

**Repositories**
Working groups should be able to create repositories as needed under their org. A project approved by the TAC should have its own org and the ability to create repos under it, regardless of which working group recommended it to the TAC.

**Funding**
Working Groups may request funding for activities from the Governing Board. 
Projects are distinct Technical Initiatives and may also directly request funding from the Governing Board (i.e. there is no request hierarchy requiring projects to go through working groups nor working groups through the TAC).
Working Groups may not request donations directly from 3rd parties but may encourage those parties to join the OpenSSF and/or engage the Governing Board to facilitate donations. _(The assumption is that there are too many laws and accounting considerations for working groups to directly handle donations)_.

**Comment by dlorenc** [comment]
> Consequently, Projects should be proposed to Working Groups who will then vet and/or revise the proposals before recommending them to the TAC.

Hmm, maybe we can flip this around a bit, or make either option available. Projects can either be proposed to a WG for a recommendation, or to the TAC directly if it's unclear which WG would be most appropriate. The TAC may then solicit input from various WGs.



> _(Note that at this time the OpenSSF is also considering a committee to review white papers. If that is approved then all authors would submit for review through that committee.)_

I don't know that we've explicitly said white papers would be in scope for that committee. I think the current intention is for it to handle "marketing" type communications, rather than technical publications. It's good we call this out here since it's still up in the air, but my preference would be to leave the governing board committee out of technical reviews like this.



> Working groups should be able to create repositories as needed under their org.
Does this imply each WG should use a separate org? I think it would be great to make one available for them, but also let them place repos in the ossf org. We've had feedback that both models are useful (keeping things in the OSSF org helps discoverability, but too many small things will actually backfire and hurt it).


> Working Groups may not request donations directly from 3rd parties but may encourage those parties to join the OpenSSF and/or engage the Governing Board to facilitate donations. _(The assumption is that there are too many laws and accounting considerations for working groups to directly handle donations)_.

Note that we do have a mechanism in the charter specifically for this case. With GB approval, WGs can do "directed fundraising" (Section 3, Paragraph vii).

What about WGs requesting companies donate things other than money? Things like cloud credits, etc. I'd like to think that's allowed. Even time from individuals could be considered a donation.

**Comment by dlorenc** [comment]
Just closing threads up - over Slack we discussed that some of the confusion is around the difference between WGs and Projects (the charter specifies both, and that they both fall under a larger category called "Technical Initiatives").

I'm wondering how important that distinction is, and if it matters for our purposes going forward. Can we use those names interchangeably? If a WG starts writing code, does it become a Project? Or do we need a formal way to switch between the two?

From my understanding of what many of the WGs are planning, most will eventually be writing some sort of code. Whether or not these efforts will be large enough to be classified as "full-fledged, top-level" projects is another question.

**Comment by david-a-wheeler** [comment]
> If a WG starts writing code, does it become a Project? Or do we need a formal way to switch between the two?

My understanding is that WGs can kick off many projects, each of which are part of their WG. A project might not fit within a WG, in which case it's free-standing and would report directly to the TAC. That doesn't make my understanding correct of course :-).

**Comment by dlorenc** [comment]
That's roughly mine too. WGs can have "lowercase p" projects. If they get large or otherwise desire, they can hop out and report directly to the TAC and become "capital P" Projects.

Maybe @mkdolan can weigh in here - I remember him explaining that there might be IP distinctions between top-level Projects and WGs at some point.

**Comment by mayakacz** [comment]
Where we're landing on this thread SGTM:
* projects can be independent or part of working groups, and can suggest to be hosted by a WG or if there is debate, ask the TAC
* technical white papers are in the scope of WGs
* WGs can have their own repos in the ossf org, and if needed, their own org

**Comment by dlorenc** [comment]
Let's handle further discussions in the PR, thanks for starting this @dcmiddle !
