### ISSUE TITLE
TAC Election Process: Chair & Rep continuity

### ISSUE THREAD

**Issue by rhaning** [ossf/tac#55]
**Proposal**
Keep Ryan Haning & Dan Lorenc as the TAC chair and rep respectively for the duration of the current term.

**Comment by dlorenc** [comment]
What is meant exactly by the remainder of the current term?

**Comment by dlorenc** [comment]
I'd be in favor of reelect chairs and (potentially board rep) to align with the new TAC schedule.

**Comment by rhaning** [comment]
I don't want to speak for @LindsayLF, but my understanding of the intention here was to keep the TAC chair and rep through the first election process and term.
@LindsayLF can you clarify this for us?

**Comment by LindsayLF** [comment]
Hi There! I believe "current term" may have been more relevant if the TAC would opt to hold elections at the 6-month mark vs. annually - meaning that the TAC Chair & Rep would stay through the first year at least.  

However, I would recommend either the TAC chair or TAC Rep stay on the TAC as a member or in the same role depending final voting structure and cadence agreed upon.

**Comment by dlorenc** [comment]
My understanding of the charter is that the TAC representative term on the board is handled in the charter already - and is fixed at one year from the date the member board seat elections took place, in section 3. b. ii. Those terms took affect on Nov. 1st.

There's some ambiguity in what happens if the "TAC rep to the GB" is no longer on the TAC, but I would read that if the "TAC rep to the GB" is no longer on the TAC, the individual should also resign from the GB. The TAC would elect a new rep in that case.

The TAC Chair election is also fixed at one year - it looks like Ryan's term started on September 1st.

I'd propose we keep things simple and avoid accidentally guaranteeing ourselves an extra year+ on the TAC. My preference is that we would handle these seats normally and replace the chair/GB rep after the elections, if either member is no longer on the TAC.
