### ISSUE TITLE
Vote: Project Alpha-Omega

### ISSUE THREAD

**Issue by rhaning** [ossf/tac#61]
The Alpha-Omega project has been proposed to the TAC and requires a vote to move forward to the Governing Board for budget approval.

TAC Reps, please provide your vote by leaving a comment on this issue with either an 'Approve' or 'Reject'.

[Proposal Document](https://docs.google.com/document/d/1u7Ps18dzu9M-HF7ZHTK6VB5jLaVJvnw6uq3o7qw5yGE/edit)

**Comment by lukehinds** [comment]
I thought we agreed on approaching a shortlist of projects first to see if they would be receptive to the idea? @jenniferfernick used the example of a phase0.

**Comment by rhaning** [comment]
@lukehinds yes, that is correct. We agreed that defining our approach to engaging with project maintainers and performing this due diligence work would be added to the proposal, and with those updates in mind, we would continue with the vote.

**Comment by jenniferfernick** [comment]
I love this proposal - another bold and visionary contribution by @scovetta!! 

**Approve**, conditional upon an initial idea-validation phase in which we get feedback on the proposed idea (especially the "Alpha" piece) from a small representative set of OSS maintainers. (This is of course the "phase 0" we discussed (@lukehinds, @rhaning) in yesterday's TAC meeting). 

Strengths:
* Comprehensive suite of efforts that complement one another well to meaningfully improve OSS security, and will likely be more consistent and efficient than one-off efforts to improve individual critical projects. 
* Combination of scalable, efficient reach ("Omega") and deeper investment ("Alpha") 
* Dedicated resources, including for project/program management, to ensure successful delivery 
* Commitment (including in the tooling-driven "Omega" phase) to not just identify vulnerabilities, but actually help write patches for them. This is very important. 

Considerations for project success:
* Ensure (through creation of "Phase 0") that this meets the security needs and intended workflows of OSS maintainers and that we uphold the OpenSSF value of being "maintainers-first". This also includes that this project should not create significant work for maintainers, ie: it needs to be well-resourced enough that they would consent and be supportive of participating in Alpha for it to proceed, but after that we as much as possible avoid making their lives harder or adding tasks that may get in the way of their other intended development activities, and offer the resources needed for meaningful and complete security contributions to be made. Our intention is to be helpful and respectful, so if we're viewed as doing otherwise, we will have failed. 
* Determine overlap with Securing Critical Projects group in OpenSSF to ensure shared vision & prevent duplication of effort 
* Given that the "Alpha" phase involves third-party security reviews, we should keep in mind that size/scope of a project could considerably impact audit cost and thus project budget 
* I'd like to see more clarification about how vulnerabilities will be identified and remediated in the Alpha phase. It is important that the work OpenSSF does through Alpha-Omega makes projects more secure in a collaborative fashion that prioritizes the security of the project and ensures that unremediated vulns are known only by the disclosing researcher and recipient project security team. This means that Alpha-Omega identification of vulnerabilities needs (1) to offer support to help remediate those vulns, and (2) to have a clear policy for how the disclosure from the "Supporters" to the project maintainers will work, to ensure that it is conducted ethically and that all parties are acting in good faith and only those with a "need to know" the undisclosed bug will do so. It may be useful to ask @SecurityCRob and the OpenSSF vuln disclosure group to help draft written guidance that is shared transparently with project maintainers so they know exactly what to expect when vulns are identified in their projects. We should also specify communication channels that don't simply drop 0day in a public GitHub issue that is normally used for non-security bug reports, for example. 
* It is EXTREMELY important that the triage portal is well-secured. We may want to see if something exists for this that meets our requirements so we wouldn't have to build from scratch. 
* There's probably many other considerations, these are just a few thoughts

**Comment by scovetta** [comment]
FYI, I've reached out to a handful of representative projects and will summarize the responses as they come in, hopefully over the next few days. If anyone else has connections to critical OSS projects that you think would be relevant, please send me a note and I can include them.

**Comment by scovetta** [comment]
**Update: I've received three responses so far.**

From a representative Python project: 
> Yes, we'd be up for entertaining this!

From a security organization:
> In our experience no one has ever rejected the help. Most projects we've worked with have welcomed us with open arms... The only resistance I've ever encountered was more so dealing with perception. Projects were worried that a review meant "getting a bunch of issues and bug reports dumped on us and then that's it". This perception has been addressed by communicating up front that the security review is a collaboration between the audit team and the project where issues are being discussed and mitigated.

From a security organization:
> ...When we come with the approach “where can we help?” there is no push back. There might be later on some “don’t have time to focus on that right now” when it comes to actually implementing things, but they were all willing to at least discuss opportunities.

**Comment by rhaning** [comment]
I approve.

**Comment by lukehinds** [comment]
Whose the representative of interest @scovetta , someone from the python foundation perhaps?

**Comment by scovetta** [comment]
@lukehinds I'd prefer to not make the names of the folks I reached out to public, but it was the maintainer of one of the most popular/recognizable Python modules. I'd be happy to share all exchanges with the TAC privately.

To be transparent, I reached out to 7 projects last Wednesday and received a response from one of them. I'm "friendly ping"-ing the remaining ones today and will anonymize and post their response here if they respond.

I also connected with two security organizations (quotes above) and started the following [thread](https://twitter.com/scovetta/status/1441856518601596935) on Twitter over the weekend:

![image](https://user-images.githubusercontent.com/732166/134946537-82beff2a-182a-4a55-a6a9-860624d8161c.png)
![image](https://user-images.githubusercontent.com/732166/134946566-e7c46d7c-5ae0-4d35-8a4a-c8ca3cf67216.png)
![image](https://user-images.githubusercontent.com/732166/134946580-689e774f-6789-410c-b71e-07afe618a1e5.png)
![image](https://user-images.githubusercontent.com/732166/134946593-bbd50b89-f481-4bd5-9942-922d56308da9.png)
![image](https://user-images.githubusercontent.com/732166/134946614-04c2fd98-a39d-40d0-99e5-c77a8f176d4c.png)
![image](https://user-images.githubusercontent.com/732166/134946629-e98d940d-288e-43b5-80f2-f9d03fe63502.png)
![image](https://user-images.githubusercontent.com/732166/134947822-20260cd1-c9f9-47ef-83a3-73d36091aae1.png)

Granted, the Twitter conversation was not targeted to "most critical" projects, nor was it asking directly, "would you accept help?", but I also didn't see anything to suggest that we far off the mark strategically. I've integrated this feedback into the proposal, but the main point, and I think this is critical for Alpha, is for us to approach each engagement with an open, learning mindset, and be willing to actively help, and not simply generate work for the maintainers. I haven't seen anything to suggest that a significant number of projects would reject help offered in good faith.

**Comment by raolakkakula** [comment]
My vote is yes if we test out the project with a small set of projects in a phased approach.  Overall I like the proposal but it's just grandeur and love to see it go agile approach of starting small.

**Comment by lukehinds** [comment]
I think the doc needs to be repurposed on what the TAC has requested and we hold off the vote until that happens.

I personally believe a proper due diligence needs to be carried out before we start discussing budgets, hiring resources and making announcements, press releases etc.

If we can in a specific way refactor the document to have it clearly outline this is to approve a preparation phase ("phase 0"), you have my approve, however right now we are voting on the entity of the doc, budget and all. 

I am not alone here, @raolakkakula and @jenniferfernick  I believe have also outlined the same, but I can't see any amendments to reflect this (do point out if I am mistaken).

**Comment by dlorenc** [comment]
In terms of "general alignment with the OpenSSF", I'm a +1.

I think the budget stuff needs more work, but my understanding is that's the role of the GB.

**Comment by lukehinds** [comment]
I am going to **abstain**, so the GB can make its decision.

My points still stand though. I think due-diligence upfront is lacking and agree with @raolakkakula, the graduer and scope would be better reduced, to test the idea first to see if it has any legs to it.

**Comment by lukehinds** [comment]
Hey, I am just thinking, how does this play out with https://security.googleblog.com/2021/10/introducing-secure-open-source-pilot.html ?

**Comment by solardiz** [comment]
Hi all. @iamamoose mentioned this project to me in a related discussion a while ago, and I finally found the time to read the proposal document referenced by @rhaning here. I don't know if it's appropriate for me (someone not involved with OpenSSF) to barge in your discussion (although it's been silent for 2 weeks now, so hopefully I won't distract you from the voting), but FWIW I have a few thoughts to contribute:

I like that the program is multi-year, presumably with intent to prolong it while it works. Is that the intent? Can it be spelled out, and with reason (funding commitments)? One of the issues with previous related efforts (such as CII) was that they were one-off, so a potential contributor/grantee would know that no matter how they perform they'd need to find another project/grant/client/job soon. I heard that this aspect was discouraging to some, resulting in potential collaboration never even starting (why start something potentially long-term if it would be forced to end in a year).

I like Alpha - this is what has been needed for years, where people/teams/companies offering software security audits and projects needing to respond to security findings can both receive funding for that work. If something like this were available 20 years ago and throughout the years, I personally and we at Openwall would have done a lot more in this area during those 20 years (we did a little bit anyway, including a few paid security audits), in either of both of these roles (can help others, and maintain projects of our own).

I think the Alpha-Omega split is reasonable.

As to Omega, I like the idea in principle, but I am concerned:

Just how many projects would realistically be covered by Omega? In one place, the proposal document mentions starting with 500. I think that's sane. However, in another place it mentions 750k+/year. I think that's insane, or at least incompatible with the document also saying that Omega would provide assistance with fixes. No way the available funding and the current market of related security services would accommodate providing assistance on fixes for this many issues per year... and here I assume it'd be 1+ identified issue per project (probably more). I think realistic goals need to be set, limited to where Omega's benefits outweigh the costs and risks.

Then, the proposal document suggests setting up a super-secure triage portal for Omega issues. Nothing can be perfectly secure, and besides the technical setup there are people. In my experience running the (linux-)distros list, besides and more importantly than a secure setup, there must exist and be enforced a policy to make issues public after a predetermined maximum time period, regardless of availability of fixes. For (linux-)distros, the maximum is currently 14 days. Google's Project Zero also does this, with a maximum of 90 days. This should be chosen such that the value of the still-embargoed information to an attacker (an APT) is diminished sufficiently that they wouldn't bother or at least wouldn't make much use of the information before the general public has an equal chance at fixing the issue or otherwise using the information.

OTOH, both (linux-)distros and Google P0 are more like Alpha than Omega. This means two things: we're reminded by these examples that a maximum embargo time should be set in Alpha as well, but we don't yet know whether the same approach works as well for Omega. Yet I think that setting up a database of forever-unpublished likely-security findings doesn't convincingly provide a good benefit vs. risk balance.

I think an example closer to Omega could be syzbot. That one makes everything public right away. So maybe that's the way to go?

I understand that making likely-security issues public without fixes might not play well with companies funding this effort. However, at least Google is OK with P0 and syzbot.

**Comment by solardiz** [comment]
Here's a different look at:

> "well what if we fall behind, and we effectively become a stockpile of untriaged but likely serious vulnerabilities?" -- that would be a big problem

Actually, if you publish the full reusable and easy to deploy source code behind Omega's setup and don't use any external randomness (only published PRNG seeds, if at all), so that others could and hopefully would use it too, then your own stockpile of _untriaged_ bugs wouldn't be of that much value - anyone could obtain exactly the same from their own setup of Omega's software (with the same PRNG seeds), if somehow they wanted to match yours, for the cost of contributing their own computing resources (which a state-sponsored APT would easily afford). Following this line of logic further, you could as well be making the purely automated findings public right away, syzbot style.

It's _triaged_ yet unfixed bugs that are of greatest value to attackers.

**Comment by lukehinds** [comment]
should we close this now, as this has since gone to the GB whom have approved?

**Comment by SecurityCRob** [comment]
+1 @dlorenc 's comment.  Can we close it out or are there further actions for the TAC to take?

**Comment by SecurityCRob** [comment]
@scovetta do you have any answers to the questions from @lukehinds and @dlorenc  above?

**Comment by david-a-wheeler** [comment]
IIRC ,the (old) TAC approved Alpha-Omega as a top-level project & the governing board approved its funding. I don't remember the dates offhand, but they should be clearly recorded in the meeting minutes. So from that perspective this specific issue should be closed.

There are some great discussions in this issue about Alpha-Omega more generally, they probably belong somewhere else though I'm glad they've happened.

**Comment by dlorenc** [comment]
I don't remember an explicit approval in a meeting, I think this issue was the approval mechanism.

**Comment by david-a-wheeler** [comment]
I thought the TAC did approve it. Some more recent text in the TAC meeting minutes assume it's an OpenSSF top-level project; See 2021-11-16 in:
https://docs.google.com/document/d/18BJlokTeG5e5ARD1VFDl5bIP75OFPCtzf77lfadQ4f0/edit

It's not clearly documented in the meeting minutes... maybe we need to review the Youtube videos?

**Comment by steiza** [comment]
Alpha-Omega has now been running for some time!

The question of where exactly it lives continues, see https://github.com/ossf/tac/issues/161#issuecomment-1583284190. As part of that issue, we'll sort out if it's an Associated Project (and if so, what that means) or if it's a Project in the Identifying Security Threats Working Group (with Special Interest Funds).
