### ISSUE TITLE
TAC Election: Seats & Candidates

### ISSUE THREAD

**Issue by rhaning** [ossf/tac#65]
- Complete refresh of the TAC, all 7 seats will be up for election.
- Anyone may self nominate by sending an email to the TAC mailing list.
- Candidates should submit a 'candidate statement' when self nominating.

**Comment by jenniferfernick** [comment]
+1 on self-nomination; candidate statements 

As discussed in today's meeting, I like the idea of self-nomination because it can help increase the diversity of our candidate pool, including new candidates or those who may not happen to have a strong network with anyone in the current TAC but who nevertheless may be great voices to add to the TAC.

I love the idea of including beyond a bio, a candidate statement also, because we can see peoples' ideas, intentions, and contributions, rather than the impressiveness of their biography or simple name recognition or whatever. Hopefully it also helps diversify our candidate pool and let us get to know newer participants too.

**Comment by jaltman** [comment]
> +1 on self-nomination; candidate statements
> 
> As discussed in today's meeting, I like the idea of self-nomination because it can help increase the diversity of our candidate pool, including new candidates or those who may not happen to have a strong network with anyone in the current TAC but who nevertheless may be great voices to add to the TAC.
> 
> I love the idea of including beyond a bio, a candidate statement also, because we can see peoples' ideas, intentions, and contributions, rather than the impressiveness of their biography or simple name recognition or whatever. Hopefully it also helps diversify our candidate pool and let us get to know newer participants too.

I agree in full.

**Comment by dlorenc** [comment]
+1 to all of this.

**Comment by AevaOnline** [comment]
+1

**Comment by david-a-wheeler** [comment]
> On Nov 16, 2021, at 6:34 PM, Ryan Haning ***@***.***> wrote:
> Complete refresh of the TAC, all 7 seats will be up for election.
> Anyone may self nominate by sending an email to the TAC mailing list.
> Candidates should submit a 'candidate statement' when self nominating.

You might want to have the TAC reps from the GB voted on first, *then* do community,
so someone voted on from the GB doesn’t try to also get voted on from the community.

--- David A. Wheeler

**Comment by estesp** [comment]
+1

**Comment by naveensrinivasan** [comment]
> I love the idea of including beyond a bio, a candidate statement also, because we can see peoples' ideas, intentions, and contributions, rather than the impressiveness of their biography or simple name recognition or whatever. Hopefully it also helps diversify our candidate pool and let us get to know newer participants too.

Love this!!

**Comment by SecurityCRob** [comment]
Do we need to circle back, formally document our process, and adjust as desired?

**Comment by torgo** [comment]
Hi folks - I would like to inject the following idea into the next TAC election process cycle. Right now the OpenSSF charter restricts TAC participation as follows:
> b) OpenSSF Members that are part of a group of Related Companies (as defined in Section 8) may have no more than two voting representatives on the TAC.
I would like to gently suggest that this should be amended to **one** voting representative rather than two. My thought process is: 
* Large companies will have many engineers participating in OpenSSF efforts and therefore will have many eligible voters in these elections
* The possibly of block voting is therefore high
* This is evidenced by the fact that we currently have two large companies that have two representatives each on the TAC
* Since the TAC is only 7 members, this has the potential to orient decisions of the TAC more towards the needs of large companies
Please note: this is not an attack on the TAC nor on any TAC member, who are all awesome individuals, and who are doing great work. Also, I recognise and appreciate that the individuals elected to the TAC take their responsibility to the OpenSSF and the community very seriously. In the long term, however, I believe this would provide for a stronger TAC and a stronger foundation. Also note: the [W3C TAG](https://w3.org/tag) group which I co-chair operates under [this constraint](https://www.w3.org/2023/Process-20230612/#AB-TAG-constraints) so there is some relevant precedent in the industry for having a more restrictive approach.

**Comment by omkhar** [comment]
to capture an item discussed at the 07/25/2023 TAC meeting:

There is a desire for transparency regarding the results of the election. There were a number of methods discussed, including publishing a stack rank (rather than vote tallies). 

Informing nominees that vote tallies will be public following the completion of voting  may strike a good balance of satisfying transparency while making the intent clear to candidates before they nominate.

**Comment by ctcpip** [comment]
As discussed briefly at today's TAC meeting, I was unable to find election results other than the list of winners.  It was mentioned that the reason for not making results public was to avoid negative perception/interpretation of the results, e.g. where a candidate receives no votes.

These are understandable concerns and I wonder if we might be able to find some middle ground where we are still mindful of that, but at the same time, improve transparency with regard to the results.  For example, perhaps a list of the rankings of the top 5 or top 10 candidates, without showing the vote counts, etc.

**Comment by SecurityCRob** [comment]
On 16Nov2023 the GC unanimously approves the standard elections cycle for all elected positions throughout the Foundation and that such a cycle is automatically amended, as new elected positions are created or deleted, on vote of approval from the GC for positions other than the GB Chair.  The TAC will be expanded to 9 seats total, 6 being elected by the community for 2year terms, and 3 appointed by the GB for 1 year terms.  For 2024, 50% of the elected seats will be for a one year term only so that going forward the TAC will cycle out 50% of members every year.  Elections will be held starting late November 2024.

https://github.com/ossf/Governance-Committee/issues/14
